server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 6
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  rocketmq:
    name-server: 192.168.88.128:9876  # RocketMQ NameServer地址
    producer:
      group: seckill-producer-group
      send-message-timeout: 3000
      retry-times-when-send-failed: 2
      retry-times-when-send-async-failed: 2
      max-message-size: 4194304  # 4MB
    consumer:
      group: seckill-consumer-group
      consume-message-batch-max-size: 1
      consume-timeout: 15000
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug